name: Docker Image CI

on:
  push:
      branches: [ "master" ]
  pull_request:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build And Push Image'
        run: |
          docker build . --tag ghcr.io/felhe/wohnen:latest
          docker push ghcr.io/felhe/wohnen:latest
